apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: greenreach/authentification_service:v1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

          # env:
          #   - name: db_root_password
          #     valueFrom:
          #       secretKeyRef:
          #         name: flaskapi-secrets
          #         key: db_root_password
          #   - name: db_name
          #     value: flaskapi

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service

spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: auth-service
  type: LoadBalancer