apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-app

  template:
    metadata:
      labels:
        app: auth-app

    spec:
      containers:
        - name: auth
          image: greenreach/authentification_service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service

spec:
  ports:
  - name: auth-port 
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: auth-app
  type: LoadBalancer