POST http://185.3.92.30:3000/register
Content-Type: application/json

{
    "username": "marius2",
    "password": "parola123"
}

###
POST http://185.3.92.30:3000/login
Content-Type: application/json

{
    "username": "marius2",
    "password": "parola123"
}

###
POST http://185.3.92.30:3000/me
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcml1cyIsImlhdCI6MTY0MTk0MzMxMywiZXhwIjoxNjQyMDI5NzEzfQ._TKYtsP-17-ZfJ4nfy4N0aVcskiLj6k_8-FHMmlSjXU"
}