POST http://212.71.236.145:3000/register
Content-Type: application/json

{
    "username": "marius2",
    "password": "parola123"
}

###
POST http://212.71.236.145:3000/login
Content-Type: application/json

{
    "username": "marius2",
    "password": "parola123"
}

###
POST http://212.71.236.145:3000/me
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcml1czIiLCJpYXQiOjE2NDIwODY0ODcsImV4cCI6MTY0MjE3Mjg4N30.IUBGo_J6EDF4-6Z5d0aoxHuE5w5RXrCD0BSB-pOSa0Q"
}