apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs
  namespace: default
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /dev/disk/by-id/scsi-0Linode_Volume_LogVolume
    server: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
---