apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-info-deployment
  labels:
    app: content-info-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-info-service

  template:
    metadata:
      labels:
        app: content-info-service

    spec:
      containers:
        - name: content-info-service
          image: greenreach/content_info_service:v1.0
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"

          # env:
          #   - name: db_root_password
          #     valueFrom:
          #       secretKeyRef:
          #         name: flaskapi-secrets
          #         key: db_root_password
          #   - name: db_name
          #     value: flaskapi

---
apiVersion: v1
kind: Service
metadata:
  name: content-info-service

spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: content-info-service
  type: LoadBalancer