apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-info-deployment
  labels:
    app: content-info-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-info-app

  template:
    metadata:
      labels:
        app: content-info-app

    spec:
      containers:
        - name: content-info
          image: greenreach/content_info_service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: content-info-service

spec:
  ports:
  - name: content-info-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: content-info-app
  type: LoadBalancer