apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app

  template:
    metadata:
      labels:
        app: frontend-app

    spec:
      containers:
        - name: frontend
          image: greenreach/geekhub_frontend:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service

spec:
  ports:
  - name: frontend-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend-app
  type: LoadBalancer