apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-deployment
  labels:
    app: file-storage-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-storage-service

  template:
    metadata:
      labels:
        app: file-storage-service

    spec:
      containers:
        - name: file-storage-service
          image: greenreach/file_storage_service:v1.0
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

          # env:
          #   - name: db_root_password
          #     valueFrom:
          #       secretKeyRef:
          #         name: flaskapi-secrets
          #         key: db_root_password
          #   - name: db_name
          #     value: flaskapi

---
apiVersion: v1
kind: Service
metadata:
  name: file-storage-service

spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: file-storage-service
  type: LoadBalancer