apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-app

  template:
    metadata:
      labels:
        app: review-app

    spec:
      containers:
        - name: review
          image: greenreach/review_service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: review-service

spec:
  ports:
  - name: review-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: review-app
  type: LoadBalancer