apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service

  template:
    metadata:
      labels:
        app: review-service

    spec:
      containers:
        - name: review-service
          image: greenreach/review_service:v1.0
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

          # env:
          #   - name: db_root_password
          #     valueFrom:
          #       secretKeyRef:
          #         name: flaskapi-secrets
          #         key: db_root_password
          #   - name: db_name
          #     value: flaskapi

---
apiVersion: v1
kind: Service
metadata:
  name: review-service

spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: review-service
  type: LoadBalancer